---
- name: "Boot all hosts"
  gather_facts: true
  hosts:  all
  become: yes
  vars:
    add_host_entries: true
    add_resolv_entries: true
  pre_tasks:
  - name: "Setting hostname"
    shell: "hostnamectl set-hostname {{ inventory_hostname }}"
  roles:
    - common
- name: "Install OSSEC Server"
  gather_facts: true
  hosts:  vg-ossec-01
  become: yes
  roles:
    - ossec-server
- name: "Install OSSEC Agent"
  gather_facts: true
  hosts:  vg-ossec-02
  become: yes
  roles:
    - ossec-agent
